version: '3.6'

volumes:
    postgres_data:
        driver: local

## Apache und PHP Content
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: .
        #image: php:8.0-apache
        volumes:
            - ./Webserver/src:/var/www/html/
        ports:
            - 80:80
        depends_on:
            - db

    ## Mysql Datenbank mit Kundenverwaltung und INitial Load
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: User
            MYSQL_USER: testuser
            MYSQL_PASSWORD: password
        ports:
            - 3307:3306
        volumes:
            - ./Database/init:/docker-entrypoint-initdb.d

    ## Adminer (Datenbanktool)
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    ## Postgresql (für Keycloak)
    postgres:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password

    ## Keycloak Auth Manager
    keycloak:
        image: quay.io/keycloak/keycloak:latest
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgres
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_SCHEMA: public
            DB_PASSWORD: password
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: Pa55w0rd
        ports:
            - 8180:8080
        depends_on:
            - postgres
            #- php-apache-environment



