version: '3.6'

volumes:
    postgres_data:
        driver: local

## Apache und PHP Content
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: .
        volumes:
            - ./Webserver/src:/var/www/html/
        ports:
            - 80:80
        depends_on:
            db:
                condition: service_healthy #service_started
            postgres:
                condition: service_healthy #service_started
            keycloak:
                condition: service_started #service_started
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://php-apache-environment:80" ]
            interval: 10s
            timeout: 180s
            retries: 5
        restart: on-failure

    ## Mysql Datenbank mit Kundenverwaltung und INitial Load
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: User
            MYSQL_USER: testuser
            MYSQL_PASSWORD: password
        ports:
            - 3307:3306
        volumes:
            - ./Database/init:/docker-entrypoint-initdb.d
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
            interval: 2s
            timeout:  2s
            retries: 3

    ## Postgresql (für Keycloak)
    postgres:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U keycloak"]
            interval: 10s
            timeout: 2s
            retries: 5

    ## Keycloak Auth Manager
    keycloak:
        image: quay.io/keycloak/keycloak:latest
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgres
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_SCHEMA: public
            DB_PASSWORD: password
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: Pa55w0rd
        ports:
            - 8180:8080
        command:
            - "-b 0.0.0.0"
            - "-Dkeycloak.import=/opt/jboss/keycloak/Master_Realm.json"
            - "-Dkeycloak.import=/opt/jboss/keycloak/CRYBOT_Realm.json"
        volumes:
            - ./Keycloak/imports/crybot:/opt/jboss/keycloak/themes/crybot
            - ./Keycloak/imports/Master_Realm.json:/opt/jboss/keycloak/Master_Realm.json
            - ./Keycloak/imports/CRYBOT_Realm.json:/opt/jboss/keycloak/CRYBOT_Realm.json

        depends_on:
            postgres:
                condition: service_healthy #service_started
        healthcheck:
            test: [ "CMD", "curl", "-f", "keycloak:8180" ]
            interval: 10s
            timeout: 3s
            retries: 5


