version: '3.6'

volumes:
    postgres_data:
        driver: local

## Apache und PHP Content
services:

## Mysql Datenbank mit Kundenverwaltung und INitial Load
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: User
            MYSQL_USER: testuser
            MYSQL_PASSWORD: password
        ports:
            - 3307:3306
        volumes:
            - ./Database/init:/docker-entrypoint-initdb.d




