name: Unit Test

on:
  push:
    branches:
      - main
      - master
jobs:
  # this runs tests without cache, is slower
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

  test-bare:
    runs-on: ubuntu-latest
    ## Wait for the DB-Cointainer to start
    needs: docker
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

  shutdowndocker:
    timeout-minutes: 0.1
    runs-on: ubuntu-latest
    needs: [docker,test-bare]
    steps:
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
