name: Unit Test

on:
  push:
    branches:
      - main
jobs:


  # this runs tests without cache, is slower
  test-bare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test